/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.study_group_service.models.dto.input;

import com.fasterxml.jackson.annotation.JsonSetter;
import lombok.Data;

/**
 * UserRegistration
 */
@Data
public class UserRegistration {
  @JsonSetter("username")
  private String username = null;

  @JsonSetter("password")
  private String password = null;

  @JsonSetter("confirmPassword")
  private String confirmPassword = null;

  public UserRegistration username(String username) {
    this.username = username;
    return this;
  }
}
